node("openshift-master"){
  env.OPENSHIFT_URL=OPENSHIFT_URL
  stage ("Checkout")
  {
        dir("openshift-prune") {
            git branch: "master", url: "https://github.com/ossimlabs/openshift-prune.git"
        }

  }    
  stage ("Publish Docker App")
  {
    withCredentials([[$class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'dockerCredentials',
                    usernameVariable: 'OPENSHIFT_USERNAME',
                    passwordVariable: 'OPENSHIFT_PASSWORD']])
    {
        // Run all tasks on the app. This includes pushing to OpenShift and S3.
        sh """
        pushd openshift-prune/scripts
        ./prune.sh
        popd
        """
    }
  }
}
