node(""){
    
  stage ("Publish Docker App")
  {
    withCredentials([[$class: 'UsernamePasswordMultiBinding',
                    credentialsId: 'dockerCredentials',
                    usernameVariable: 'OPENSHIFT_USERNAME',
                    passwordVariable: 'OPENSHIFT_PASSWORD']])
    {
        // Run all tasks on the app. This includes pushing to OpenShift and S3.
        sh """
        oc login ${OPENSHIFT_URL} --username="${env.OPENSHIFT_USERNAME}" --password="${env.OPENSHIFT_PASSWORD}" """
    }
  }
}
